#!/usr/bin/env python
# coding: utf-8

# In[2]:


import numpy as np
import pandas as pd
import seaborn as sbs


# In[3]:


dtfr=pd.read_csv("D:\Datasheet\emails.csv")


# In[4]:


dtfr


# # Drop all columns except Email No. and the

# In[5]:


dtfr=dtfr.iloc[:,:2]


# In[6]:


dtfr


# In[7]:


dtfr.shape


# In[8]:


dtfr.dropna()


# In[9]:


dtfr.describe()


# In[ ]:





# # Data Preprocessing

# In[10]:


dtfr.isnull().sum()


# In[11]:


dtfr.isnull().values.any()


# In[12]:


dtfr.the.value_counts()


# # Data and output

# In[13]:


x=dtfr['Email No.']


# In[14]:


y=dtfr['the']


# In[15]:


y


# In[16]:


dtfr.head(10)


# # Data visualization

# In[17]:


from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x=cv.fit_transform(x)


# In[18]:


x.toarray()


# # dividing Traing and testting data

# In[19]:


from sklearn.model_selection import train_test_split


# In[20]:


xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)


# # Model selection

# In[21]:


from sklearn.naive_bayes import MultinomialNB


# In[22]:


gnb=MultinomialNB()
gnb.fit(xtrain,ytrain)


# In[23]:


gnb.score(xtest,ytest)


# In[24]:


from sklearn.naive_bayes import BernoulliNB
bnb=BernoulliNB()
bnb.fit(xtrain,ytrain)


# In[25]:


bnb.score(xtest,ytest)


# # K Fold validation

# In[27]:


from sklearn.model_selection import cross_val_score
cv_score=cross_val_score(gnb,x,y,cv=10)


# In[28]:


cv_score


# In[29]:


cv_score.mean()


# In[ ]:




